'use client';
import { useState } from 'react';
import { ChevronDownIcon } from '@heroicons/react/24/solid';

const faqs = [
  {
    question: "What is ReelCap, and how can it help my indie business?",
    answer: "..."
  },
  {
    question: "Do I need any design skills to use ReelCap?",
    answer: "..."
  },
  {
    question: "How does the trend analysis feature work?",
    answer: "..."
  },
  {
    question: "Can I customize the memes generated by ReelCap?",
    answer: "..."
  },
  {
    question: "What if I don't have time to manage my social media accounts?",
    answer: "..."
  },
  {
    question: "Is there a money-back guarantee if I'm not satisfied with my subscription?",
    answer: "..."
  }
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section id="faq" className="py-24 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <h2 className="text-4xl font-bold text-center mb-16">
          Frequently Asked Questions
        </h2>
        
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div key={index} className="border-b border-gray-200">
              <button
                className="w-full py-6 flex justify-between items-center text-left"
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
              >
                <span className="text-lg font-medium">{faq.question}</span>
                <ChevronDownIcon 
                  className={`w-5 h-5 transform transition-transform ${
                    openIndex === index ? 'rotate-180' : ''
                  }`}
                />
              </button>
              {openIndex === index && (
                <div className="pb-6 text-gray-600">
                  {faq.answer}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
} 